import ProjectDescription

let config = Config(
    compatibleXcodeVersions: .upToNextMajor("13.2.1"),
    swiftVersion: "5.4.2",
    plugins: [
//        .local(path: .relativeToRoot("Plugin/UtilityPlugin"))
    ]
//    ,[
//    generationOptions: [ProjectDescription.Config.GenerationOptions.options()
//        .xcodeProjectName("\(.projectName)"),
//        .organizationName("havi"),
//        .disableAutogeneratedSchemes,
//        .disableSynthesizedResourceAccessors,
//    ]
)
