import ProjectDescription

let config = Config(
    compatibleXcodeVersions: .upToNextMajor("13.2.1"),
    swiftVersion: "5.4.2",
    plugins: [
//        .local(path: .relativeToRoot("Plugin/UtilityPlugin"))
    ],
    generationOptions: [
        .xcodeProjectName("\(.projectName)"),
        .organizationName("havi"),
        .disableAutogeneratedSchemes,
        .disableSynthesizedResourceAccessors,
    ]
)
